"""
Chapter 1 — EDA
Reads data.json (generated by procure.py) and prints summary statistics.
Run procure.py first.
"""
import json, os
import pandas as pd

DIR = os.path.dirname(os.path.abspath(__file__))

with open(os.path.join(DIR, "data.json")) as f:
    df = pd.DataFrame(json.load(f))

print("=== Chapter 1 — Life Expectancy at Birth by State ===\n")
print(df[["state", "life_expectancy", "imr", "region"]].sort_values("life_expectancy").to_string(index=False))

no_putrajaya = df[df.gadm_name != "Putrajaya"]
print(f"\nRange  : {no_putrajaya.life_expectancy.min():.1f} – {no_putrajaya.life_expectancy.max():.1f} yrs (excl. Putrajaya)")
print(f"Gap    : {no_putrajaya.life_expectancy.max() - no_putrajaya.life_expectancy.min():.1f} yrs")
print(f"Mean   : {no_putrajaya.life_expectancy.mean():.1f} yrs")
print(f"Data year: {df.year.iloc[0]}")

print("\nBottom 3 (excl. Putrajaya):")
print(no_putrajaya.nsmallest(3, "life_expectancy")[["state", "life_expectancy"]].to_string(index=False))
print("\nTop 3:")
print(df.nlargest(3, "life_expectancy")[["state", "life_expectancy"]].to_string(index=False))

print("\nBy region:")
print(df.groupby("region")["life_expectancy"].mean().round(1).sort_values())
